# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
  
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) + np.array(Y)
 
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### 2. Write a Python Program to Multiply Two Matrices?

In [2]:
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
 
# result will be 3x4
 
result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


### 3. Write a Python Program to Transpose a Matrix?

In [5]:
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

A= np.array(A)

B=A.T
B

array([[12,  4,  7],
       [ 7,  5,  8],
       [ 3,  6,  9]])


### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [7]:
def F(S):
    W = S.split(" ")
    for i in range(len(W)):
        W[i] = W[i].lower()
    W.sort()
 
    # return the sorted words
    return ' '.join(W)
 
# Driver code
S = "I am Girl"
print(F(S))

am girl i


### 5. Write a Python Program to Remove Punctuation From a String?

In [11]:
import string
 
test_str = 'I, am, the best : for ! Cooking ;'
 
test_str = test_str.translate(str.maketrans('', '', string.punctuation))
print(test_str)

I am the best  for  Cooking 
